// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

export type HealthResponse = {
  /**
   * Service status
   */
  status: string
}

export type Health = unknown

/**
 * Health check endpoints
 */
export type Health2 = unknown

export type GetHealthData = {
  body?: never
  path?: never
  query?: never
  url: '/api/healthz'
}

export type GetHealthResponses = {
  /**
   * Service is healthy
   */
  200: HealthResponse
}

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses]
